
WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR +1 FROM TIME WHERE HOUR <23
)


(SELECT HOUR, (0) AS COUNT FROM TIME
WHERE HOUR NOT IN( SELECT HOUR(DATETIME) FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
)

UNION ALL
SELECT HOUR(DATETIME), COUNT(*) FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME))
ORDER BY HOUR